name: Rain Alert

on:
  schedule:
    - cron: "0 4 * * *"  
  workflow_dispatch:       

jobs:
  run-rain-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install requests twilio

      - name: Run script
        env:
          OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
          ACC_SID: ${{ secrets.ACC_SID }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          MY_NUM: ${{ secrets.MY_NUM }}
        run: python main.py
